### PR TITLE
Update to latest cloud sandbox API

### PR DESCRIPTION
**Pull request by tarruda**
Signed-off-by: Thiago Padilha <thiago@calyptia.com>

### CODE REVIEW

**Review by nicolasparada — APPROVED** [review]

**Review by nicolasparada — COMMENTED** [review]
Didn't you also add an option so set the function name?
`callback`

Could you add it?

**Comment by tarruda** [comment]
> Could you add it?

I'm not sure how to go about this. Should I add an additional parameter to `Run()` or change it to receive an opts object containing events, code and callback name?

Keep in mind that both  options will result in a breaking API change, and in this case might be better to go ahead and change `FluentBitLog` so it matches the new API (it should have `tag`, `timestamp` and `record`). That would allow me to pass `FluentBitLog` directly to the json serializer, without having to convert first.

**Comment by tarruda** [comment]
Note that I had created `event` private struct to prevent API breaking change, but if we are going to break in order to change callback name, might as well go ahead and make necessary changes to https://github.com/calyptia/api

**Comment by nicolasparada** [comment]
You can change the method signature. Maybe receive a struct with all the options.

Doesn't matter if the client library breaks, we use `go.mod` and we can upgrade whenever we want 👍

But this is good to merge, we can do it later in another PR.

**Comment by tarruda** [comment]
Still need an additional approve to merge

**Pull request merged**
